version = "1.0"

[[packages]]
name = "gnome-shell"
comment = "49.5-1 crashes when a monitor is removed"

[[packages.conditions]]
key = "evr"
comparator = "="
value = "49.4-1.fc43"

[[packages]]
name = "mutter"
comment = "supposedly related to gnome-shell crash"

[[packages.conditions]]
key = "evr"
comparator = "="
value = "49.4-1.fc43"
