name: Build Container

on:
  repository_dispatch:
    types:
      - rebuild

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - test
          - prod
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
          - environment: dev
            previous: library
          - environment: test
            previous: dev
          - environment: prod
            previous: test
    steps:
      - name: test
        run: |
          echo ${{ matrix.environment }}
          echo ${{ matrix.previous }}
          echo ${{ matrix.os }}
          echo ${{ matrix.arch }}
